config/routes.rb
Rails.application.routes.draw do
  resources :todo_statuses
  resources :todos, except: %w[new] do
    collection { post :bulk_insert }
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/csv_importable.rb
require "csv"

module CsvImportable
  extend ActiveSupport::Concern

  module ClassMethods
    def csv_import(file, parser)
      # CSV から目的のモデルインスタンスを生成
      csv_records = parser.new(Rails.logger).call(file)

      # バリデーションを実行
      errors = collect_validate_errors(csv_records)

      # エラーが無ければ bulk insert 実行
      # rubocop:disable Rails/SkipsModelValidations
      # `collect_validate_errors` にてバリデーション済みなので警告を抑制
      insert_all(csv_records.map(&:model)) if errors.empty?
      # rubocop:enable Rails/SkipsModelValidations

      errors
    end

    def collect_validate_errors(model_with_lineno)
      # 返却用配列
      errors = []

      # バリデーションを実行し、エラーがあればエラーメッセージを返却用配列へ格納
      model_with_lineno.each do |mwl|
        model = new(mwl.model)
        is_valid = model.validate

        messages = model.errors.full_messages.map do |message|
          "lineno: #{mwl.lineno}, name: #{mwl.model['name']}, message: #{message}"
        end

        errors.concat(messages) unless is_valid
      end

      errors
    end
  end
end

app/models/csv_record.rb
class CsvRecord
  attr_accessor :lineno, :model

  def initialize(lineno, model)
    @lineno = lineno
    @model = model
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  include CsvImportable

  def self.ransackable_attributes(_auth_object = nil)
    %w[name todo_status_id id created_at updated_at]
  end

  belongs_to :todo_status, optional: true
  validates :name, presence: true
  validates :todo_status_id, presence: true
  validates_with ForeignKeyValidator,
                 child_model_class: Todo,
                 child_attribute_symbol: :todo_status_id,
                 parent_model_class: TodoStatus,
                 enum_string: TodoStatus.all.map(&:name)
end

app/models/todo_status.rb
class TodoStatus < ApplicationRecord
  def self.ransackable_attributes(_auth_object = nil)
    %w[name id created_at updated_at]
  end

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_statuses_controller.rb
class TodoStatusesController < ApplicationController
  include Pagy::Backend
  before_action :set_todo_status, only: %i[show edit update destroy]

  # GET /todo_statuses
  def index
    @todo_statuses = TodoStatus
      .all
    @q = @todo_statuses.ransack(params[:q])
    @q.sorts = "id asc" if @q.sorts.empty?
    @pagy, @todo_statuses = pagy(@q.result, page: params[:page], items: params[:items])
  end

  # GET /todo_statuses/1
  def show
  end

  # GET /todo_statuses/new
  def new
    @todo_status = TodoStatus.new
  end

  # GET /todo_statuses/1/edit
  def edit
  end

  # POST /todo_statuses
  def create
    @todo_status = TodoStatus.new(todo_status_params)

    if @todo_status.save
      redirect_to @todo_status, notice: t("controller.create.success", model: TodoStatus.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /todo_statuses/1
  def update
    if @todo_status.update(todo_status_params)
      redirect_to @todo_status, notice: t("controller.edit.success", model: TodoStatus.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /todo_statuses/1
  def destroy
    @todo_status.destroy
    redirect_to todo_statuses_url, notice: t("controller.destroy.success", model: TodoStatus.model_name.human)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_todo_status
      @todo_status = TodoStatus
        .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_status_params
      params.require(:todo_status).permit(:name)
    end
end

app/controllers/todos_controller.rb
require "./app/services/csv/todo_csv_parser"

class TodosController < ApplicationController
  include Pagy::Backend
  before_action :set_todo, only: %i[show edit update destroy]

  # GET /todos
  def index
    @todos = Todo
      .eager_load(:todo_status)
    @q = @todos.ransack(params[:q])
    @q.sorts = "id asc" if @q.sorts.empty?
    @pagy, @todos = pagy(@q.result, page: params[:page], items: params[:items])
  end

  # GET /todos/1
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
    @todo.todo_status_id = TodoStatusesHelper::NEW
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  def create
    @todo = Todo.new(todo_params)

    render :new, status: :unprocessable_entity unless @todo.save
  end

  # PATCH/PUT /todos/1
  def update
    if @todo.update(todo_params)
      redirect_to @todo, notice: t("controller.edit.success", model: Todo.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
    redirect_to todos_url, notice: t("controller.destroy.success", model: Todo.model_name.human)
  end

  # POST /todo_bulk_insert
  def bulk_insert
    errors = Todo.csv_import(params[:file], parser)

    if errors.empty?
      flash.notice = t("controller.create.success", model: Todo.model_name.human)
    else
      flash.alert = errors
    end

    redirect_to todos_url
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo
        .eager_load(:todo_status)
        .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :todo_status_id)
    end

    def parser
      Csv::TodoCsvParser
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def turbo_stream_flash
    turbo_stream.append "flashes", partial: "flash"
  end
end

app/helpers/todo_statuses_helper.rb
module TodoStatusesHelper
  include Pagy::Frontend

  NEW = 1
  IN_PROGRESS = 2
  DONE = 3
end

app/helpers/todos_helper.rb
module TodosHelper
  include Pagy::Frontend
end

app/views/application/_flash.html.erb
<% if notice %>
  <div class="alert alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-dismissible" style="color: red">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <h2><%= t("errors.template.header", model: Todo.model_name.human, count: flash.alert.count) %></h2>

    <ul>
    <% flash.alert.each do |error| %>
      <li><%= error %></li>
    <%- end -%>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YaTodo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_statuses/_form.html.erb
<%= form_with(model: todo_status, html: { class: %w[form-control form-control-sm] }) do |form| -%>
  <%- if todo_status.errors.any? -%>
  <div style="color: red">
    <h2><%= t("errors.template.header", model: TodoStatus.model_name.human, count: todo_status.errors.count) %></h2>

    <ul>
    <% todo_status.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <%- end -%>
    </ul>
  </div>
  <%- end -%>

  <%- if request.path_info.include?("edit") -%>
  <div>
    <%= form.label :id, style: "display: block" %>
    <div class="ps-2">
      <%= form.number_field :id, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.label :name, style: "display: block" %>
    <div class="ps-2">
      <%= form.text_field :name, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <%- if request.path_info.include?("edit") %>
  <div>
    <%= form.label :created_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :created_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :updated_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.submit class: %w[btn btn-primary] %>
  </div>
<% end %>

app/views/todo_statuses/_todo_status.html.erb
<div id="<%= dom_id todo_status %>">
  <table class="table table-hover">
    <tr>
      <td>
        <strong>Id:</strong>
      </td>
      <td>
        <%= todo_status.id %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= TodoStatus.human_attribute_name(:name) %>
        </strong>
      </td>
      <td>
        <%= todo_status.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= TodoStatus.human_attribute_name(:created_at) %>
        </strong>
      </td>
      <td>
        <%= todo_status.created_at && l(todo_status.created_at) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= TodoStatus.human_attribute_name(:updated_at) %>
        </strong>
      </td>
      <td>
        <%= todo_status.updated_at && l(todo_status.updated_at) %>
      </td>
    </tr>
  </table>
</div>

app/views/todo_statuses/edit.html.erb
<h1><%= t("view.edit.title", model: TodoStatus.model_name.human) %></h1>
<%= render "form", todo_status: @todo_status %>

<br>

<div>
  <%= link_to t("view.edit.move_to_show", model: TodoStatus.model_name.human), @todo_status %> |
  <%= link_to t("view.edit.move_to_index", model: TodoStatus.model_name.human.pluralize), todo_statuses_path %>
</div>

<script type="text/javascript">
  document.addEventListener('turbo:load', function() {
    setupTomSelectForSingleSelect();
  });
  document.addEventListener('turbo:render', function() {
    setupTomSelectForSingleSelect();
  });
</script>

app/views/todo_statuses/index.html.erb
<div style="display: flex;flex-direction: column;height: 100vh;">

  <header class="main-content-header">
    <p style="color: green"><%= notice %></p>

    <h1><%= TodoStatus.model_name.human %><%= link_to "", new_todo_status_path, class: %w[bi bi-plus-circle-fill ms-2] %></h1>

  <div class="accordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="search-form-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#search-form"
          aria-expanded="false"
          aria-controls="search-form"><%= t("view.index.search_condition") %></button>
      </h2>
      <div id="search-form" class="panel panel-default accordion-collapse collapse" aria-labelledby="headingOne">
<%= search_form_for @q, html: { class: %w[form-control form-control-sm], data: { turbo_frame: "list" } } do |f| %>
        <div>
          <%= f.label :id_eq %>
          <div class="ps-2">
            <%= f.number_field :id_eq, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :name_cont %>
          <div class="ps-2">
            <%= f.search_field :name_cont, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :created_at %>
          <div class="ps-2">
            <%= f.datetime_field :created_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :created_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :updated_at %>
          <div class="ps-2">
            <%= f.datetime_field :updated_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :updated_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <%= f.hidden_field :items, id: "f-items", value: params[:items] %>
        <%= f.submit class: %w[btn btn-primary] %>
        <input
          type="reset"
          class="btn btn-primary"
          onclick="clear_form(arguments[0], this)"
          value="<%= t("helpers.submit.clear") %>">
<%- end -%>
      </div>
    </div>
  </header>

  <main style="flex-grow: 1;flex-shrink: 1;overflow-y: auto;">
<%= turbo_frame_tag "list" do %>
  <div id="todo_statuses" class="text-nowrap">
    <table class="table table-hover text-nowrap">
      <thead class="table-light sticky-top">
        <th><%= sort_link(@q, :id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :name, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :created_at, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :updated_at, default_order: :asc, class: "d-block") %></th>
        <th><%= t("view.index.operation") %></th>
      </thead>
      <tbody>
  <%- @todo_statuses.each do |todo_status| %>
        <tr
          tabindex="0"
          role="button"
          onkeypress="handleEnterKeypressListIten(arguments[0], this, '<%= url_target(nil, todo_status).to_s %>')"
          onclick="handleClickListItem(arguments[0], this, '<%= url_target(nil, todo_status).to_s %>')">
          <td><%= todo_status.id %></td>
          <td><%= todo_status.name %></td>
          <td><%= todo_status.created_at && l(todo_status.created_at) %></td>
          <td><%= todo_status.updated_at && l(todo_status.updated_at) %></td>
          <td>
            <%= button_to(
                  t("helpers.submit.delete"),
                  todo_status,
                  method: :delete,
                  tabindex: 0,
                  class: %w[btn btn-primary],
                  onclick: "handleDeleteListItem(arguments[0], this)",
                  data: { turbo_confirm: t("helpers.dialog.delete", id: todo_status.id) }
                ) %>
          </td>
        </tr>
  <%- end %>
      </tbody>
    </table>
  </div>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_items_selector_js(@pagy, item_name: "Todo status".pluralize(@pagy.count), pagy_id: "pagy-items-selector") %>
    <%= link_to(
          t("view.index.update_item_per_page", model: TodoStatus.model_name.human),
          "javascript:void(0);",
          onClick: "updateItemPerPage(arguments[0],
          this)"
        ) %>
  </div>
<% end %>
  </main>
</div>

<script type="text/javascript">
  document.addEventListener('turbo:load', function() {
    setupTomSelectForMultiSelect();
  });
  document.addEventListener('turbo:render', function() {
    setupTomSelectForMultiSelect();
  });
</script>

app/views/todo_statuses/new.html.erb
<h1><%= t("view.new.title", model: TodoStatus.model_name.human) %></h1>
<%= render "form", todo_status: @todo_status %>

<br>

<div>
  <%= link_to t("view.new.move_to_index", model: TodoStatus.model_name.human.pluralize), todo_statuses_path %>
</div>

<script type="text/javascript">
  document.addEventListener('turbo:load', function() {
    setupTomSelectForSingleSelect();
  });
  document.addEventListener('turbo:render', function() {
    setupTomSelectForSingleSelect();
  });
</script>

app/views/todo_statuses/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= TodoStatus.model_name.human %></h1>

<%= render @todo_status %>

<div>
  <%= link_to t("view.show.move_to_update", model: TodoStatus.model_name.human), edit_todo_status_path(@todo_status) %> |
  <%= link_to t("view.show.move_to_index", model: TodoStatus.model_name.human.pluralize), todo_statuses_path %>

  <%= button_to t("helpers.submit.delete"),
                @todo_status,
                method: :delete,
                class: %w[btn btn-primary],
                data: { turbo_confirm: t("helpers.dialog.delete", id: @todo_status.id) } %>
</div>

app/views/todos/_edit_form.html.erb
<%= form_with(model: todo, html: { class: %w[form-control form-control-sm] }) do |form| -%>
  <%- if todo.errors.any? -%>
  <div class="alert alert-dismissible" style="color: red">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <h2><%= t("errors.template.header", model: Todo.model_name.human, count: todo.errors.count) %></h2>

    <ul>
    <% todo.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <%- end -%>
    </ul>
  </div>
  <%- end -%>

  <div>
    <%= form.label :id, style: "display: block" %>
    <div class="ps-2">
      <%= form.number_field :id, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <div class="ps-2">
      <%= form.text_field :name, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label Todo.reflect_on_association(:todo_status).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            Todo.reflect_on_association(:todo_status).foreign_key,
            Todo.reflect_on_association(:todo_status).klass.all,
            :id,
            :name,
            { include_blank: "選択なし" }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label :created_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :created_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :updated_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.submit class: %w[btn btn-primary] %>
  </div>
<% end %>

app/views/todos/_form.html.erb
<%= turbo_frame_tag todo do %>
  <%= form_with(model: todo, html: { class: %w[form-control form-control-sm] }) do |form| -%>
    <%- if todo.errors.any? -%>
    <div class="alert alert-dismissible" style="color: red">
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      <h2><%= t("errors.template.header", model: Todo.model_name.human, count: todo.errors.count) %></h2>

      <ul>
      <% todo.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <%- end -%>
      </ul>
    </div>
    <%- end -%>

    <%- if request.path_info.include?("edit") -%>
    <div>
      <%= form.label :id, style: "display: block" %>
      <div class="ps-2">
        <%= form.number_field :id, class: %w[form-control form-control-sm], disabled: true %>
      </div>
    </div>
    <%- end -%>
    <div>
      <%= form.label :name, style: "display: block" %>
      <div class="ps-2">
        <%= form.text_field :name, class: %w[form-control form-control-sm] %>
      </div>
    </div>
    <div>
      <%= form.label Todo.reflect_on_association(:todo_status).foreign_key %>
      <div class="ps-2">
        <%= form.collection_select(
              Todo.reflect_on_association(:todo_status).foreign_key,
              Todo.reflect_on_association(:todo_status).klass.all,
              :id,
              :name,
              { include_blank: "選択なし" }
            ) %>
      </div>
    </div>
    <%- if request.path_info.include?("edit") %>
    <div>
      <%= form.label :created_at, style: "display: block" %>
      <div class="ps-2">
        <%= form.datetime_field :created_at, class: %w[form-control form-control-sm], disabled: true %>
      </div>
    </div>
    <div>
      <%= form.label :updated_at, style: "display: block" %>
      <div class="ps-2">
        <%= form.datetime_field :updated_at, class: %w[form-control form-control-sm], disabled: true %>
      </div>
    </div>
    <%- end -%>
    <div>
      <%= form.submit class: %w[btn btn-primary] %>
    </div>
  <% end %>
<% end %>

app/views/todos/_list_item.html.erb
<tr id="<%= dom_id todo %>"
  tabindex="0"
  role="button"
  onkeypress="handleEnterKeypressListIten(arguments[0], this, '<%= url_target(nil, todo).to_s %>')"
  onclick="handleClickListItem(arguments[0], this, '<%= url_target(nil, todo).to_s %>')">
  <td><%= todo.id %></td>
  <td><%= todo.name %></td>
  <td><%= todo.todo_status.name %></td>
  <td><%= todo.created_at && l(todo.created_at) %></td>
  <td><%= todo.updated_at && l(todo.updated_at) %></td>
  <td>
    <%= button_to(
          t("helpers.submit.delete"),
          todo,
          method: :delete,
          tabindex: 0,
          class: %w[btn btn-primary],
          onclick: "handleDeleteListItem(arguments[0], this)",
          data: { turbo_confirm: t("helpers.dialog.delete", id: todo.id) }
        ) %>
  </td>
</tr>

app/views/todos/_todo.html.erb
<table class="table table-hover">
  <tr>
    <td>
      <strong>Id:</strong>
    </td>
    <td>
      <%= todo.id %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>
        <%= Todo.human_attribute_name(:name) %>
      </strong>
    </td>
    <td>
      <%= todo.name %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>
        <%= Todo.human_attribute_name(:todo_status_id) %>
      </strong>
    </td>
    <td>
      <%= todo.todo_status.name %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>
        <%= Todo.human_attribute_name(:created_at) %>
      </strong>
    </td>
    <td>
      <%= todo.created_at && l(todo.created_at) %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>
        <%= Todo.human_attribute_name(:updated_at) %>
      </strong>
    </td>
    <td>
      <%= todo.updated_at && l(todo.updated_at) %>
    </td>
  </tr>
</table>

app/views/todos/create.turbo_stream.erb
<%# 新規作成フォームのリセット %>
<%= turbo_stream.update "new-todo-container",
      partial: "todos/form",
      locals: { todo: Todo.new(name: "", todo_status_id: 1) } %>

<%# 現在表示されているリストの先頭に追加した要素を挿入 %>
<%= turbo_stream.prepend "todos-tbody",
      partial: "todos/list_item",
      locals: { todo: @todo } %>

<%# Flashを表示 %>
<%= turbo_stream_flash %>

app/views/todos/edit.html.erb
<h1><%= t("view.edit.title", model: Todo.model_name.human) %></h1>
<%= render "edit_form", todo: @todo %>

<br>

<div>
  <%= link_to t("view.edit.move_to_show", model: Todo.model_name.human), @todo %> |
  <%= link_to t("view.edit.move_to_index", model: Todo.model_name.human.pluralize), todos_path %>
</div>

app/views/todos/index.html.erb
<div style="display: flex;flex-direction: column;height: 100vh;">

  <header class="main-content-header">

    <h1><%= Todo.model_name.human %></h1>

    <div id="flashes">
      <%= render "flash" %>
    </div>

    <%= turbo_frame_tag "new-todo-container" do %>
      <%= render "form", todo: Todo.new(name: "", todo_status_id: TodoStatusesHelper::NEW) %>
    <% end %>

    <%= form_tag bulk_insert_todos_path, multipart: true do %>
      <%= label_tag "CSVインポート:" %>
      <%= file_field_tag :file, accept: "text/csv" %>
      <%= submit_tag "インポート", class: %w[btn btn-primary] %>
    <% end %>

  <div class="accordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="search-form-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#search-form"
          aria-expanded="false"
          aria-controls="search-form"><%= t("view.index.search_condition") %></button>
      </h2>
      <div id="search-form" class="panel panel-default accordion-collapse collapse" aria-labelledby="headingOne">
<%= search_form_for @q, html: { class: %w[form-control form-control-sm], data: { turbo_frame: "list" } } do |f| %>
        <div>
          <%= f.label :id_eq %>
          <div class="ps-2">
            <%= f.number_field :id_eq, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :name_cont %>
          <div class="ps-2">
            <%= f.search_field :name_cont, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label Todo.reflect_on_association(:todo_status).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  Todo.reflect_on_association(:todo_status).foreign_key + "_in".to_s,
                  Todo.reflect_on_association(:todo_status).klass.all,
                  :id,
                  :name,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label :created_at %>
          <div class="ps-2">
            <%= f.datetime_field :created_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :created_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :updated_at %>
          <div class="ps-2">
            <%= f.datetime_field :updated_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :updated_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <%= f.hidden_field :items, id: "f-items", value: params[:items] %>
        <%= f.submit class: %w[btn btn-primary] %>
        <input
          type="reset"
          class="btn btn-primary"
          onclick="clear_form(arguments[0], this)"
          value="<%= t("helpers.submit.clear") %>">
<%- end -%>
      </div>
    </div>
  </header>

  <main style="flex-grow: 1;flex-shrink: 1;overflow-y: auto;">
<%= turbo_frame_tag "list" do %>
  <div id="todos" class="text-nowrap">
    <table class="table table-hover text-nowrap">
      <thead class="table-light sticky-top">
        <th><%= sort_link(@q, :id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :name, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :todo_status_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :created_at, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :updated_at, default_order: :asc, class: "d-block") %></th>
        <th><%= t("view.index.operation") %></th>
      </thead>
      <tbody id="todos-tbody">
      <%= render partial: "list_item", collection: @todos, as: :todo %>
      </tbody>
    </table>
  </div>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_items_selector_js(@pagy, item_name: "Todo".pluralize(@pagy.count), pagy_id: "pagy-items-selector") %>
    <%= link_to(
          t("view.index.update_item_per_page", model: Todo.model_name.human),
          "javascript:void(0);",
          onClick: "updateItemPerPage(arguments[0],
          this)"
        ) %>
  </div>
<% end %>
  </main>
</div>

app/views/todos/new.html.erb
<h1><%= t("view.new.title", model: Todo.model_name.human) %></h1>
<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to t("view.new.move_to_index", model: Todo.model_name.human.pluralize), todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= Todo.model_name.human %></h1>

<%= render @todo %>

<div>
  <%= link_to t("view.show.move_to_update", model: Todo.model_name.human), edit_todo_path(@todo) %> |
  <%= link_to t("view.show.move_to_index", model: Todo.model_name.human.pluralize), todos_path %>

  <%= button_to t("helpers.submit.delete"),
                @todo,
                method: :delete,
                class: %w[btn btn-primary],
                data: { turbo_confirm: t("helpers.dialog.delete", id: @todo.id) } %>
</div>